sudo: required
language: generic 

services:
    - docker

before_install:
  - docker build -t stpiep/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stpiep/react-test npm run test

after_success:
  - docker build -t stpiep/multi-client ./client
  - docker build -t stpiep/multi-nginx ./nginx
  - docker build -t stpiep/multi-server ./server
  - docker build -t stpiep/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stpiep/multi-client
  - docker push stpiep/multi-nginx
  - docker push stpiep/multi-server
  - docker push stpiep/multi-worker
